# Generated by Django 4.0.5 on 2022-07-07 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_img', models.ImageField(blank=True, upload_to='profile_avatar')),
                ('department', models.CharField(choices=[('PR', 'PRODUCTION'), ('QA', 'QUALITY'), ('PE', 'PRODUCTION ENGINEERING'), ('SM', 'SALES MARKETING'), ('SE', 'SAFETY'), ('LP', 'LOGISTIC'), ('NA', 'UNDEFINED')], default='NA', max_length=2)),
                ('grade', models.CharField(choices=[('OP', 'OPERATIONAL'), ('SP', 'SPECIALIST'), ('TL', 'TEAM LEADER'), ('SU', 'SUPERVISOR'), ('MN', 'MANAGER')], default='OP', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
