# Generated by Django 4.0.5 on 2022-07-09 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_department', models.CharField(choices=[('PR', 'PRODUCTION'), ('QA', 'QUALITY'), ('PE', 'PRODUCTION ENGINEERING'), ('SM', 'SALES MARKETING'), ('SE', 'SAFETY'), ('LP', 'LOGISTIC'), ('NA', 'UNDEFINED')], default='NA', max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('importance', models.CharField(choices=[('HI', 'CRITICAL'), ('NO', 'NORMAL'), ('LO', 'LOW')], default='LO', max_length=2)),
                ('task_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_creator', to=settings.AUTH_USER_MODEL)),
                ('task_executor', models.ManyToManyField(related_name='task_executor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
