# Generated by Django 4.0.5 on 2022-07-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('HI', 'CRITICAL'), ('NO', 'NORMAL'), ('LO', 'LOW')], default='LO', max_length=4),
        ),
    ]
