# Generated by Django 4.0.5 on 2022-07-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NA', 'NOT ASSIGNED'), ('INP', 'IN PROGRESS'), ('DONE', 'DONE')], default='LO', max_length=4),
        ),
    ]
