# Generated by Django 4.0.5 on 2022-07-11 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0005_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_creator', to='accounts.userinfo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_executor',
            field=models.ManyToManyField(blank=True, related_name='task_executor', to='accounts.userinfo'),
        ),
    ]
