# Generated by Django 4.0.5 on 2022-07-12 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0006_alter_task_task_creator_alter_task_task_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_executor',
        ),
        migrations.AddField(
            model_name='task',
            name='task_executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_executor', to='accounts.userinfo'),
        ),
    ]
