# Generated by Django 4.0.5 on 2022-07-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
